spring:
  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: true
    thymeleaf:
      cache: true

  datasource:
#    url: ${DATASOURCE}
    url: jdbc:mariadb://database-1.cii1ws7cibkw.ap-northeast-2.rds.amazonaws.com/okmall
    driver-class-name: org.mariadb.jdbc.Driver
    username: yun970
    password: scc95953048
#    username: ${AWS_RDS_USER}
#    password: ${AWS_RDS_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

jasypt:
  encryptor:
    baen: jasyptStringEncryptor

kakao:
#  key: ${kakao_key}
  key: dbstjrwns1
